### PR TITLE
fix: support for empty headless lines

### PR DESCRIPTION
**Pull request by adamperkowski**

### CODE REVIEW

**Review by nnyyxxxx — CHANGES_REQUESTED** [review]
image
image

weird behavior

**Comment by adamperkowski** [comment]
> weird behavior

Doesn't happen for me. Can you share the code?

**Comment by nnyyxxxx** [comment]
> > weird behavior
> 
> Doesn't happen for me. Can you share the code?

if two values are called with a headless value it will generate a = , this will always happen because add_entry_headless requires two values

**Comment by nnyyxxxx** [comment]
adding a return; fixes this issue

**Comment by adamperkowski** [comment]
Pull the branch (or look at the code)
It's fixing this with `if` and `else`.

**Comment by nnyyxxxx** [comment]
> Pull the branch (or look at the code) It's fixing this with `if` and `else`.

i tested this diff, and my issues with it are above

**Comment by nnyyxxxx** [comment]
turns out github was showing this previously applied commit https://github.com/nnyyxxxx/hyprparser/commit/156bd1e6ac4531e34c9618a6b922e4ea007fbac2 sorry, lol

**Pull request merged**
